spring:
  cloud:
    config:
      override-system-properties: false
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: iznek3737
  application:
    name: roads-service
server:
  port: 8071

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
    register-with-eureka: true
    fetch-registry: true