spring:
  application:
    name: activities-service
  data:
    mongodb:
      username: root
      password: iznek
      host: localhost
      port: 27017
      database: activities
      authentication-database: admin
server:
  port: 8070
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka