spring:
  cloud:
    config:
      override-system-properties: false
  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/information
    username: root
    password: iznek
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    clean-disabled: false
    baseline-on-migrate: true
    baseline-version: 1
  application:
    name: information-service

server:
  port: 8050

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
    register-with-eureka: true
    fetch-registry: true

application:
  config:
    activities-url: http://ACTIVITIES-SERVICE/api/v1/activites